# Generated by Django 3.2.5 on 2021-08-03 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210725_0750'),
        ('projects', '0007_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='proje',
            new_name='project',
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
