# Generated by Django 3.2.5 on 2021-08-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210804_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
